-- Add digital signature column to influence_users table
ALTER TABLE public.influence_users 
ADD COLUMN nda_digital_signature text null;

-- Add comment for clarity
COMMENT ON COLUMN public.influence_users.nda_digital_signature IS 'Digital signature for membership agreement (text input)';

-- Add source tracking JSONB column to influence_users table
ALTER TABLE public.influence_users
ADD COLUMN source_tracking jsonb null;

-- Add comment for source tracking column
COMMENT ON COLUMN public.influence_users.source_tracking IS 'JSONB object containing all source tracking data (source, reiaName, socialPlatform, referrerName, wordOfMouth, otherSource, utmSource, utmMedium, utmCampaign, srcBook)';

-- Add GIN index for efficient JSONB queries
CREATE INDEX IF NOT EXISTS idx_influence_users_source_tracking ON public.influence_users USING GIN (source_tracking);

-- Create webhook_events table for audit trail
CREATE TABLE IF NOT EXISTS public.webhook_events (
  id bigint generated by default as identity not null,
  stripe_event_id text unique,
  event_type text not null,
  event_data jsonb not null,
  processed boolean default false,
  processed_at timestamp with time zone,
  error_message text,
  created_at timestamp with time zone not null default now(),
  constraint webhook_events_pkey primary key (id)
) TABLESPACE pg_default;

-- Add index for performance
CREATE INDEX IF NOT EXISTS idx_webhook_events_stripe_event_id ON public.webhook_events(stripe_event_id);
CREATE INDEX IF NOT EXISTS idx_webhook_events_processed ON public.webhook_events(processed);
